### ISSUE TITLE
Bug: reading null object

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#47]
Steps to Reproduce:
- Go to page 2 with an empty local storage

```md
chat.js:131 2
chat.js:98  Uncaught TypeError: Cannot read properties of null (reading '2')
    at rebuildChat (chat.js:98:25)
    at HTMLButtonElement.<anonymous> (chat.js:134:9)
rebuildChat @ chat.js:98
(anonymous) @ chat.js:134
```

**Comment by henryzhang03** [comment]
no longer relevant
